### ISSUE TITLE
Push project to maven central

### ISSUE THREAD

**Issue by kokospalme** [fauxpark/oled-core#3]
Hello :)
Is it possible to push the repository to maven central? This would make it a lot easier to work with your project. I already followed some forum-posts but had no luck…

**Comment by cljk** [comment]
Why not just checkout the project and install to your local repo via 


```
mvn install 
```

**Comment by fauxpark** [comment]
I've set up GitHub Packages: https://github.com/fauxpark/oled-core/packages/1975164
Let me know how that works.

**Comment by kokospalme** [comment]
thank you for the quick reply. I cloned your project into a local folder, then built a jar-file with ```mvn install ```, put that jar-file into my projecr sourcefolder and linked that into the ```pom.xml```-file, following [this](https://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-to-a-maven-project) Post.

Now I get the following error when I start my project with the minimal **code**:
```
Transport transport = new I2CTransport(-1, 1, 0x3D);
SSD1306 ssd1306 = new SSD1306(128, 64, transport);
Graphics graphics = ssd1306.getGraphics();

graphics.text(20, 20, new CodePage1252(), "Hello world!");
```

**the Exception:**
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/pi4j/config/Config
	at org.deepsymmetry.jbce.Main.main(Main.java:214)
Caused by: java.lang.ClassNotFoundException: com.pi4j.config.Config
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
```

I already installed PiGpio and Java...
My system is a RasPi 3B+ running raspberry pi OS lite

Did I miss something?
**edit**
Yes, I forgot these two dependencies in my ```pom.xml```-file:
```
        <dependency>
            <groupId>com.pi4j</groupId>
            <artifactId>pi4j-plugin-pigpio</artifactId>
            <version>2.4.0</version>
        </dependency>

        <dependency>
            <groupId>com.pi4j</groupId>
            <artifactId>pi4j-plugin</artifactId>
            <version>2.4.0</version>
            <type>pom</type>
        </dependency>
```
